### ISSUE TITLE
Banning issue 

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStats#1]
Looking at the ban list there are a few people on the list that have apparently been banned multiple time Since? Such as nard whos statistic shows up 7 times In a row. They are exact copies of the ban and description but show up multiple times?

**Comment by lmas** [comment]
Multiple entries will show up for Job-Bans for a guy in the list because the guy was banned from multiple jobs at the same time. I'll try and play around with either showing the job a guy was banned from, or simple just show one job-ban entry.

**Comment by BlueSushii** [comment]
While your fixing that. couldn't we make it so it would actually show the in game characters name and even the exact time they were banned. These are just suggestions?

**Comment by lmas** [comment]
IC name isn't stored but the ban time is easy to add. It's a lot of information to show already, so adding more makes it harder to read info at a glance. I'll see what I can do.

**Comment by lmas** [comment]
Does this work?
![bans.png](http://i.imgur.com/3C69ryZ.png)

It shows the banned job instead and the time of the ban on the right above the ban message.

**Comment by BlueSushii** [comment]
It looks better thank you.
nice job on the website though.
