### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStats#5]
Shows what a players antagonist objectives for that round.

**Comment by lmas** [comment]
Gotta rewrite the whole antag list to fit in the objectives too. Getting clogged in there too D:

**Comment by BlueSushii** [comment]
Could make it so it's more of a drop down arrow text box to conserve space

**Comment by lmas** [comment]
The game doesn't store the antag objectives in the database so there's currently no way for us to show them on the pages.
Feel free to reopen this when someone decides to store the objectives.
